### ISSUE TITLE
你好，请问能否拨冗为项目更新数据库。

### ISSUE THREAD

**Issue by chovy-p** [lulyqqqq/oj-backend-microservice#1]
尊敬的作者你好，我正在学习您的这个项目，并尝试在本地复现，然而您上传的版本数据库获取都是通过远程sql服务器，现在已经无法连接，能否拨冗为项目更新本地部署的数据库

**Comment by lulyqqqq** [comment]
目前我的服务器过期了，表SQL并不能找到，我需要寻找一下，请等待

**Comment by lulyqqqq** [comment]
https://github.com/lulyqqqq/oj-backend/tree/main/sql 你好，这是单体服务的sql，是通用的，才解决你的问他非常抱歉
